version: ~> 1.0

os: linux
dist: xenial
arch: amd64
language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

script:
  - java --version
  - ./mvnw clean install
  - ./mvnw test
  - bash <(curl -s https://codecov.io/bash)